services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./conf/certs/:/etc/nginx/certs
    ports:
      - "${NGINX_PORT}:443"
    depends_on:
      - "api"
  httpd:
    image: httpd
    restart: always
    volumes:
      - ..:/usr/local/apache2/htdocs/
    ports:
      - "${FILE_SERVER_PORT}:80"
