services:  
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/service/data
      - ./src:/service/src
      - ./node_modules:/service/node_modules
    environment: []
    ports: []